### PR TITLE
[DevTools] Fix killshells behavior

### PR DESCRIPTION
**Pull request by mikeshardmind**
Not doing any testing of this right now. TLDR: you can't cancel an ongoing `concurrent.futures.Future`

Should work.

### CODE REVIEW

**Comment by jack1142** [comment]
Very quick test with `shelld ping google.com` failed on two fronts:
1. Bot doesn't type while the command runs which makes it hard to figure out whether command still runs.
2. `[p]killshells` still doesn't seem to kill the running process. Also, killing the process manually after running `[p]killshells`command will no longer make it send the output of ran command.

On bright side, the cog no longer prevents the bot from shutting down.

**Comment by mikeshardmind** [comment]
Thanks for that info. The version I just pushed should probably address that, but I'm not really in a position to be testing it right now.

**Comment by jack1142** [comment]
Update: bot is now typing while command runs and `[p]killshells` makes it stop typing but the process is still not killed after that command is ran.

**Comment by mikeshardmind** [comment]
I probably need to redesign this with a combination of a singular worker process and daemon threads spawned by this worker process. At least without doing platform-specific things to circumvent limitations of the exposed python API.

**Pull request closed without merging**
