### PR TITLE
[Draft] Code cleanup

### LINKED ISSUE #109: Code cleanup
The recent issue with:
d82e9fa and the subsequent fix 2a27e1a shows how fragile some old workarounds in the code are with regard to modifications.

At some point, the entire existing code needs to be stripped of any no-longer necessary workarounds.

This was a fragile conversion that broke in an unexpected way due to a "quick fix", when it should have been replaced with the more robust Union converters the moment the repo was no longer supporting a red version which did not have access to those.

There are definitely more things like this in the code which should be handled before they cause the next issue where a small change has unexpected side-effects.

### PR DESCRIPTION
**Pull request by DiscordLiz**
This is a draft PR to discuss changes.

Things being done (discussed elsewhere so far):

- Continue using black, not reformatting numeric literals
- Docstrings should be standardized: numpy docs for internal use functions, user-appropriate formatted output for commands, command groups, and cogs.
- Prefer existing solutions in upstream code as appropriate.
- Target code for compatibility with python3.7+, Red-DiscordBot 3.1+
- Remove any compatibility layers which existed for old versions.
- Add better exception handling.
- Handle expected potential exceptions with less broad catches.
- Code in this repository should run under mypy, excepting for upstream lack of support in red-discordbot and discord.py

This will close #109 

Cogs which are ready for review and testing:

- AntiMentionSpam

Things which will be done at the end:

- Configure updated checks for new requirements.

### CODE REVIEW

**Comment by mikeshardmind** [comment]
Thanks again for getting this started.

I think putting the target at 3.1.0 for Red may be appropriate depending on the time required to go through and ensure everything is working as intended for this, the current repository state can be tagged for 3.0.1 use if that route is chosen.

**Comment by mikeshardmind** [comment]
I went ahead and added a mypy config and made a small tweak. Assuming behavior wasn't unintentionally broken, antimentionspam didnt have anything else which needed doing AFAIK.

**Comment by mikeshardmind** [comment]
This is now dependent on changes to be included in 3.1 of Red

**Comment by mikeshardmind** [comment]
Some work with this might need further modifications if this is to be the PR to get the repo into a good state for 3.1 of Red-DiscordBot depending on if https://github.com/Rapptz/discord.py/commit/caf3d17d4aa3ce45435bb96ea6d99317bfef8618 will be included in the version of discord.py used by 3.1

I'd advise (some) caution with changes on this, but this is mostly a quick thing to account for.

**Comment by DiscordLiz** [comment]
No breaking changes in 3.1 to cog behavior. There will be deprecations. You already added a 3.1 dependency, so I can make changes to not have those warnings.

The exclusions you added in mypy are making a lot of things not get checked at all. Do you want to create stub files for these methods and objects?

**Comment by mikeshardmind** [comment]
Eventually, I'd prefer stubs for discord.py and inline type hints for anything interacting with red's config. the mypy config can be modified as that's being added to this.

**Comment by DiscordLiz** [comment]
I'm not going to manually type all of this, and stubgen's results without allowing imports leave a lot of manual work. Can't just import because of unguarded module code in both discord and red. I switched my bot over to running under a monkeytype context manager. I'll modify whatever stubs that spits out later.

**Comment by mikeshardmind** [comment]
We cant use https://github.com/Rapptz/discord.py/pull/1497 100% as is for this, but it's a damn good starting point, and would be usable in the future.  (We need to adjust the stubs to match the vendored version (or if it exists, find a state of that PR which corresponds) until we can use the version of discord.py which would be released on pypi)

A lot of Red is already typed, and I got a tacit :+1: for a PR which would type all external APIs if you feel going about it that way would be more productive @DiscordLiz 

Point you brought up in VC about unsafe imports and stubgen is possible to ignore soon, but also not neccessary since red can support strong typehints without having to worry about python3.5 support, meaning this could be done without import.

I don't know what the feeling would be for adding typing_extensions into red, and there are a few cases where Red should use it, so if you want to go that route, reach out to toby about it or make an issue.

**Comment by DiscordLiz** [comment]
@mikeshardmind you have some large sections marked with a TODO. Do you want to work on those or just lay out the ideas you had for handling those ?

**Comment by mikeshardmind** [comment]
I'll finish cleanup of bansync, rolemanagement, and relays. Scheduler shouldn't need much beyond typehinting, but if you notice something in any of those which I don't handle, let me know. Everything else is fair game right now for improvement, but I know I took some shortcuts with the others which aren't immediately obvious without having worked with it.

**Comment by mikeshardmind** [comment]
As discussed in discord, this set of changes is getting a little large, and splitting the goal of typing this in full from the cleanup makes sense to do right now. Merging the current state, but this does not mean there may not be more which needs doing.

**Pull request merged**
